
const SCALE_MODEL = "RD-903";

const HEALTHPLANET_API_CLIENT_ID = "19056.074auNWIiO.apps.healthplanet.jp";
const HEALTHPLANET_API_CLIENT_SECRET = "1711774921818-GHVjEMvDUQR3LGP3xUVPPmwcwd1RkK0TSXUt4VcF";

const GOOGLE_API_CLIENT_ID = "*****";
const GOOGLE_API_CLIENT_SECRET = "*****";

const FITBIT_API_CLIENT_ID = "*****";
const FITBIT_API_CLIENT_SECRET = "*****";

function setProps(){
  const property = PropertiesService.getScriptProperties();
  property.setProperty('HEALTHPLANET_API_CLIENT_ID',HEALTHPLANET_API_CLIENT_ID);
  property.setProperty('HEALTHPLANET_API_CLIENT_SECRET',HEALTHPLANET_API_CLIENT_SECRET);
  property.setProperty('GOOGLE_API_CLIENT_ID',GOOGLE_API_CLIENT_ID);
  property.setProperty('GOOGLE_API_CLIENT_SECRET',GOOGLE_API_CLIENT_SECRET);
  property.setProperty('FITBIT_API_CLIENT_ID',FITBIT_API_CLIENT_ID);
  property.setProperty('FITBIT_API_CLIENT_SECRET',FITBIT_API_CLIENT_SECRET);
}
